// <auto-generated />
namespace enelex3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kalibracija_cetvrta_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kalibracija_cetvrta_));
        
        string IMigrationMetadata.Id
        {
            get { return "201904040729266_kalibracija_cetvrta_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
