// <auto-generated />
namespace enelex3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TrainTable_IsActive_LastUpdatedOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrainTable_IsActive_LastUpdatedOn));
        
        string IMigrationMetadata.Id
        {
            get { return "202012011005383_TrainTable_IsActive_LastUpdatedOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
